### ISSUE TITLE
五塵来降 3,4周目報酬在庫数報告

### ISSUE THREAD

**Issue by 9c5s** [terry-u16/schale-inventory-management#38]
![MuMu12-20240926-061851](https://github.com/user-attachments/assets/eeb1f9e3-4cb7-470b-a634-e20d9e4d82d3)
![MuMu12-20240926-061934](https://github.com/user-attachments/assets/a9219411-6fd4-4a0d-a88d-f4fd1f907512)

3周目
`3×3` ×1
`1×4` ×3
`2×1` ×2

4周目
1周目と同様

4周目を見る限り今回も4～6周目は1～3周目と同様と思われます。

**Comment by terry-u16** [comment]
反映しましたー。情報のご提供どうもありがとうございました！
